# tasks file
---
- name: install
  ansible.builtin.apt:
    name: "{{ sysctl_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - sysctl
    - sysctl-install

- name: set sysctl settings
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: true
    state: "{{ item.state | default('present') }}"
    sysctl_file: "{{ item.file | default('/etc/sysctl.conf') }}"
  with_items: "{{ sysctl_settings }}"
  tags:
    - configuration
    - sysctl
    - sysctl-settings

- name: set sysctl settings (per file)
  ansible.posix.sysctl:
    name: "{{ item.1.name }}"
    value: "{{ item.1.value }}"
    reload: true
    state: "{{ item.1.state | default('present') }}"
    sysctl_file: "{{ item.0.file }}"
  with_subelements:
    - "{{ sysctl_settings_d }}"
    - settings
  tags:
    - configuration
    - sysctl
    - sysctl-settings
